/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- find total customers by state
SELECT 
	customer_state,
	COUNT(customer_unique_id) total_customers
FROM gold.dim_customers
GROUP BY customer_state
ORDER BY total_customers DESC

-- find total orders by product categories
SELECT
	COALESCE(p.product_category_name, 'N/A') product_category_name,
	COUNT(DISTINCT s.order_id) nr_orders
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
	ON s.product_id = p.product_id
GROUP BY p.product_category_name
ORDER BY nr_orders DESC

-- what is the total revenue generated for each category?
SELECT 
	--s.product_id,
	COALESCE(p.product_category_name, 'N/A') product_category_name,
	SUM(price + freight_value) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
	ON s.product_id = p.product_id
WHERE s.order_status = 'delivered'
GROUP BY p.product_category_name
ORDER BY total_revenue DESC


-- find total revenue is generated by each customer
SELECT 
	COALESCE(c.customer_unique_id, 'Unknown') customer_unique_id,
	SUM(price + freight_value) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_id = c.customer_id
WHERE s.order_status = 'delivered'
GROUP BY customer_unique_id, customer_state
ORDER BY total_revenue DESC

-- what is the distribution of sold items across states?
SELECT
	c.customer_state,
	COUNT(s.order_item_id) total_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_id = c.customer_id
WHERE s.order_status = 'delivered'
GROUP BY customer_state
ORDER BY total_items DESC;
